# Generated by Django 4.2.4 on 2023-09-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_donor_delete_donorregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
