# Generated by Django 4.2.4 on 2023-09-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('blood_type', models.CharField(max_length=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donor_history', models.CharField(max_length=3)),
                ('difficulty', models.CharField(max_length=3)),
                ('donated_before', models.CharField(max_length=3)),
                ('allergies', models.CharField(max_length=3)),
                ('alcohol_drugs', models.CharField(max_length=3)),
                ('jail', models.CharField(max_length=3)),
                ('surgery_or_transfusion', models.CharField(max_length=3)),
                ('diseased', models.CharField(max_length=3)),
                ('hiv_aids', models.CharField(max_length=3)),
                ('pregnant_or_abortion', models.CharField(blank=True, max_length=3, null=True)),
                ('child_less_than_one_year', models.CharField(blank=True, max_length=3, null=True)),
                ('menstruation', models.CharField(blank=True, max_length=3, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.donor')),
            ],
        ),
    ]
