# Generated by Django 4.2.4 on 2023-09-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_donorresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
