# Generated by Django 4.2.4 on 2023-09-10 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_donorresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DonorResponse',
        ),
    ]
