# Generated by Django 4.2.4 on 2023-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_donorresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(max_length=100)),
                ('contactPerson', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('gpsCoordinates', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=100)),
                ('hospitalURL', models.URLField(blank=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/uploads/')),
            ],
        ),
    ]
