# Generated by Django 4.2.4 on 2023-09-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_bloodtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtype',
            name='blood_type',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
