# Generated by Django 4.2.4 on 2023-09-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_bloodtype_blood_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalRegister',
        ),
    ]
